### ISSUE TITLE
Refresh bug when enlarging media

### ISSUE THREAD

**Issue by bruhhhwarrior** [Aliucord/Aliucord#429]
### What happens when the bug or crash occurs?

Whenever i tap on an image and the close it again to go back to Chat my discord does this odd refresh thing. This issue started appearing right after i updated my phone to the latest android/oneui version

https://github.com/Aliucord/Aliucord/assets/160191126/6dd45af4-2383-479d-93b3-72060dffc877

### What is the expected behaviour?

For it to not refresh when i exit the picture

### How do you recreate this bug or crash?

Tap on any media inside a chat to enlarge it and then exit it, it does the refresh (on latest android&OneUi

### Crash-log

N.a

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by jedenastka** [comment]
This is confirmed to be an Android 14 issue and is fixed in a later update.

Update your OS, or wait for an update if not available.

**Comment by lnp5131** [comment]
> This is confirmed to be an Android 14 issue and is fixed in a later update.
> 
> Update your OS, or wait for an update if not available.

Currently on Android 15 beta 2.2, build AP31.240426.023.B4
This is not fixed and has been a bug for months. Seems to be something else.

**Comment by Rykita** [comment]
Managed to get this on Android 13 and OneUI 5.1

**Comment by Magnisimus** [comment]
Bug also appears on Oneplus 13 OxygenOS 15
